// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0v5LKvRWavHANX7kDGcswqIbr0rTGlM',
    appId: '1:752527519367:web:9a58fea6a2a8cd0fa9d222',
    messagingSenderId: '752527519367',
    projectId: 'flutter-ecommerce-f7c33',
    authDomain: 'flutter-ecommerce-f7c33.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-f7c33.appspot.com',
    measurementId: 'G-ZWEZ2Y0VZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaR6pzmZc4vmNxAjjfjHhnSnfPALFsPc',
    appId: '1:752527519367:android:2bf02af34834e6afa9d222',
    messagingSenderId: '752527519367',
    projectId: 'flutter-ecommerce-f7c33',
    storageBucket: 'flutter-ecommerce-f7c33.appspot.com',
  );
}
